export const fonts = {
  thin: 'Trirong-Thin',
  thinItalic: 'Trirong-ThinItalic',
  extraLight: 'Trirong-ExtraLight',
  extraLightItalic: 'Trirong-ExtraLightItalic',
  light: 'Trirong-Light',
  lightItalic: 'Trirong-LightItalic',
  regular: 'Trirong-Regular',
  medium: 'Trirong-Medium',
  mediumItalic: 'Trirong-MediumItalic',
  semiBold: 'Trirong-SemiBold',
  semiBoldItalic: 'Trirong-SemiBoldItalic',
  bold: 'Trirong-Bold',
  boldItalic: 'Trirong-BoldItalic',
  extraBold: 'Trirong-ExtraBold',
  extraBoldItalic: 'Trirong-ExtraBoldItalic',
  black: 'Trirong-Black',
  blackItalic: 'Trirong-BlackItalic',
}
